name: cfdna-meth
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.23
  - pandas=1.5
  - scipy=1.10
  - scikit-learn=1.3
  - matplotlib=3.7
  - pybedtools=0.9
  - pysam=0.22
  - bedtools
  - tqdm=4.66
  - h5py
  - tensorflow=2.12.*
  - p-tqdm=1.4.0
  - optuna=4.6.0
  - optuna-integration[tfkeras]