name: cfdna-meth
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy=1.23
  - pandas=1.5
  - scipy=1.10
  - scikit-learn=1.3
  - matplotlib=3.7
  - pybedtools=0.9
  - pysam=0.22
  - bedtools
  - tqdm=4.66
  - h5py
  - pip:
      - tensorflow==2.12.1
      - p_tqdm==1.4.0
